### ISSUE TITLE
assert_contains! 

### ISSUE THREAD

**Issue by aaronabramov** [aaronabramov/k9#27]
basic prototype of the fn

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a9a307bab62baa5bc6e6823ebc60b15c

also makes me thing that we'll need `assert_contains_value!` and `assert_contains_key!` macros for maps!

@TheWebDevel

**Comment by TheWebDevel** [comment]
haha. Sure! That'd be awesome.
