### ISSUE TITLE
assert_equal does not handle comparing vectors to arrays

### ISSUE THREAD

**Issue by gregtatum** [aaronabramov/k9#57]
This is a parity issue with `assert_eq!`

```
// This works:
assert_eq!(vec![1, 2, 3], [1, 2, 3]);

// This does not:
assert_equal!(vec![1, 2, 3], [1, 2, 3]);
```

```
error[E0308]: mismatched types
   --> src/sampler.rs:429:38
    |
429 |         assert_equal!(vec![1, 2, 3], [1, 2, 3]);
    |                                      ^^^^^^^^^
    |                                      |
    |                                      expected struct `std::vec::Vec`, found array `[{integer}; 3]`
    |                                      help: try using a conversion method: `[1, 2, 3].to_vec()`
    |
    = note: expected struct `std::vec::Vec<{integer}>`
                found array `[{integer}; 3]`
```

**Comment by aaronabramov** [comment]
interesting! i didn't even know you could do this with `assert_eq!`. i'll need to dig into the code to see how it's done there

**Comment by gregtatum** [comment]
Hah, yeah I was a bit surprised myself. I just did a mass search and replace in my project, and I hit this one and the trailing comment issue. Otherwise things are muuuuuch more readable compared to the built-ins.

**Comment by aaronabramov** [comment]
yeah! trailing comma is a  known issue, but the current fix would mean adding a macro branch for each assertion.

also i added `assert_matches_inline_snapshot!` that i haven't documented yet if you want to try, since i remember you preferred inline snaps to a separate file 😛

**Comment by wez** [comment]
I also ran into this while migrating from the `pretty_assertions` crate; maybe worth taking a peek to see what that crate is doing?

**Comment by aaronabramov** [comment]
i guess comparing references will just work for this case
fixed in https://github.com/aaronabramov/k9/pull/69
