### ISSUE TITLE
☂️ DX Discussion

### ISSUE THREAD

**Issue by jsjoeio** [aaronabramov/k9#6]
These are my notes and thoughts after trying out `k9`.
- wish it showed PASS like Jest
- show docs on hover in IDE (like other crates)
- better error message for snapshot failure (when no snapshot present)
- couldn't get snapshot assertion to work with example from docs (i blame myself)
- also, could explain the `_r` assertions better and when you might want to use one 

## README
- could be nice to have a [quick walkthrough](https://github.com/facebook/jest#getting-started) like jest
- add installation instructions

**Comment by aaronabramov** [comment]
those are all really good!
i'd love to get the `PASS` labels, but that will require changing the actual runner, which is deeply integrated with cargo. It should be possible, but will require quite a lot of low level rust hacking!

i'll try to address all other points as well!

**Comment by aaronabramov** [comment]
https://github.com/aaronabramov/k9/issues/84 adding
