### ISSUE TITLE
`assert_eq!(left, right, format, args...)` parity

### ISSUE THREAD

**Issue by wez** [aaronabramov/k9#67]
The standard assertion macros generally pass the error message and arguments to the `panic!` macro.
`k9` just seems to allow for a lone string without formatting, which means that migrating this example from the bottom of the docs:

https://doc.rust-lang.org/std/macro.assert_eq.html

```rust
assert_eq!(a, b, "we are testing addition with {} and {}", a, b);
```

to k9 needs to done like this:

```rust
assert_equal!(a, b, format!("we are testing addition with {} and {}", a, b));
```

**Comment by aaronabramov** [comment]
good find! fixed in https://github.com/aaronabramov/k9/pull/68
