### ISSUE TITLE
better error message for snapshot failure (when no snapshot present)

### ISSUE THREAD

**Issue by aaronabramov** [aaronabramov/k9#84]

**Comment by aaronabramov** [comment]
Right now if snapshot doesn't exist it'll just be a message that you need to update it.
it would be nice to show what the snapshot value (that would've been written) would look like

**Comment by aaronabramov** [comment]
@TheWebDevel

**Comment by TheWebDevel** [comment]
Gotcha!

**Comment by TheWebDevel** [comment]
WIP!

**Comment by aaronabramov** [comment]
fixed in https://github.com/aaronabramov/k9/pull/117
