### ISSUE TITLE
assert_matches_snapshot needs Display impl

### ISSUE THREAD

**Issue by MarinPostma** [aaronabramov/k9#92]
It seems that `assert_matches_snapshot!(T)` needs T to implement `Display`. This is a pretty restrictive requirement IMO, and `Debug` should suffice.

The current workaround id to `format!` T :`assert_matches_snapshot!(format!("{:?}"))`, but this should not be necessary.

What do you think?

**Comment by aaronabramov** [comment]
yes! i'm thinking about separating display and debug into two macros. The problem with using `Debug` by default is that all multiline strings will be printed as `A\nB\nC` instead of 
```
A
B
C
```

**Comment by MarinPostma** [comment]
Uhm I hadn't though about that, same goes with pretty print?

**Comment by aaronabramov** [comment]
yup https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4199f25b9649ff175e9920f5cf5887ea

**Comment by aaronabramov** [comment]
fixed with `snapshot!()` macro
